apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-system
  template:
    metadata:
      labels:
        app: transaction-system
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: spring-container
          image: tt5t5ttt/transaction-system:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-system
spec:
  selector:
    app: transaction-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
